# Generated by Django 6.0.2 on 2026-03-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproject',
            name='likes',
            field=models.ManyToManyField(related_name='likes_finished_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='finished_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_project_comments', to='projects.finishedproject'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_group_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishedproject',
            name='project_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_finished_projects', to='projects.projectgroup'),
        ),
        migrations.AddField(
            model_name='projectgroupcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project_group_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgroupcomment',
            name='project_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_group_comments', to='projects.projectgroup'),
        ),
        migrations.AddField(
            model_name='projectidea',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_project_ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectidea',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_project_ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='project_idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_group_project_idea', to='projects.projectidea'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='project_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_idea_comments', to='projects.projectidea'),
        ),
        migrations.AddField(
            model_name='imageproject',
            name='project_idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_projects', to='projects.projectidea'),
        ),
        migrations.AddField(
            model_name='projectidea',
            name='tags',
            field=models.ManyToManyField(related_name='tags_project_ideas', to='projects.tag'),
        ),
        migrations.AddField(
            model_name='finishedproject',
            name='tags',
            field=models.ManyToManyField(related_name='tags_finished_projects', to='projects.tag'),
        ),
        migrations.AddConstraint(
            model_name='projectgroup',
            constraint=models.UniqueConstraint(fields=('name', 'project_idea'), name='unique_project_group_name'),
        ),
        migrations.AddConstraint(
            model_name='projectcomment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_project__isnull', True), ('project_idea__isnull', False)), models.Q(('finished_project__isnull', False), ('project_idea__isnull', True)), _connector='OR'), name='comment_must_belong_to_idea_or_finished_project'),
        ),
    ]
