# Generated by Django 6.0.2 on 2026-02-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectideacomment',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
