# Generated by Django 6.0.2 on 2026-02-19 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('finished_on', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(related_name='likes_finished_projects', to=settings.AUTH_USER_MODEL)),
                ('project_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_finished_projects', to='projects.projectgroup')),
                ('tags', models.ManyToManyField(related_name='tags_finished_projects', to='projects.tag')),
            ],
        ),
    ]
